### PR TITLE
fix: Plugin route Sidebar styled error

### LINKED ISSUE #1107: [Site]: route /plugins, has styled error
### Current State

**Description of the current state/issue**:
the sidebar style is `position: fixed`, When the page is scrolled to the bottom, the sidebar will overlap with the footer

**Link to the page**:
https://apisix.apache.org/plugins/

**Screenshots (if relevant)**:
image

### Desired State

**Description of the change you are proposing**:

use Affix type, dynamically calculate the height of parent elements instead of the whole document

### Would you like to fix this issue?

Yes! Count me in

### PR DESCRIPTION
**Pull request by barchielAbyss**
Fixes: [#1107](https://github.com/apache/apisix-website/issues/1107)

Changes:
add Affix Componet 2 fix Sidebar in scorll to page bottom styled error 

Screenshots of the change:
## in before:
image

## in after:
image

### CODE REVIEW

File: website/src/components/UI/Affix.tsx [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+};
+
+const Affix: FC<Props> = (props) => {
+  const { style, children } = props;
+  const [hasCssSticky, SetHasCssSticky] = useState(true);
+  useEffect(() => {
+    SetHasCssSticky(CSS.supports('position', 'sticky'));
+  });
+
+  const positionStyle = getPositionStyle(hasCssSticky, style);
```
Comment (barchielAbyss) [inline website/src/components/UI/Affix.tsx]: @SkyeYoung 

I don't konw there is how to run, Do I need to set `getPositionStyle` 2 `useEffect`?

Comment (SkyeYoung) [reply website/src/components/UI/Affix.tsx]: > I don't konw there is how to run, Do I need to set `getPositionStyle` 2 `useEffect`?

You can try 🤔

File: website/src/components/UI/Affix.tsx [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+    ...defaultStyles,
+  };
+};
+
+const Affix: FC<Props> = (props) => {
+  const { style, children } = props;
+  const [hasCssSticky, SetHasCssSticky] = useState(true);
+  useEffect(() => {
+    SetHasCssSticky(CSS.supports('position', 'sticky'));
+  });
```
Comment (SkyeYoung) [inline website/src/components/UI/Affix.tsx]: You may need the help of this document https://reactjs.org/docs/hooks-reference.html#timing-of-effects.

Since I didn't write most of the original code, and I haven't tried to improve them, many of them are negative examples, so please don't learn how they are written.

**Review by SkyeYoung — CHANGES_REQUESTED** [review]

**Comment by SkyeYoung** [comment]
> Fixes: #[1107]
> #1107

to `Fixes: #1107`

File: website/src/components/UI/Affix.tsx [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+    position: 'absolute',
+  };
+
+  return {
+    ...positionStyle,
+    ...defaultStyles,
+  };
+};
+
+const Affix: FC<Props> = (props) => {
```
Comment (SkyeYoung) [inline website/src/components/UI/Affix.tsx]: just use `React.FC` type, no need `Props`

File: website/src/components/UI/Affix.tsx [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+  const { style, children } = props;
+  const [hasCssSticky, SetHasCssSticky] = useState(true);
+  useEffect(() => {
+    SetHasCssSticky(CSS.supports('position', 'sticky'));
+  });
+
+  const positionStyle = getPositionStyle(hasCssSticky, style);
+
+  const defaultHeight = parseInt(`${style.top}`, 10);
```
Comment (SkyeYoung) [inline website/src/components/UI/Affix.tsx]: `${style.top}` really?

File: website/src/components/UI/Affix.tsx [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+
+import { getDomStyle } from '../../utils';
+
+interface Props {
+  style: CSSProperties;
+  children: ReactNode;
+}
+
+const AffixContent = styled.div`
+`;
```
Comment (SkyeYoung) [inline website/src/components/UI/Affix.tsx]:
```suggestion
const AffixContent = styled.div``;
```

**Review by SkyeYoung — CHANGES_REQUESTED** [review]

**Comment by SkyeYoung** [comment]
React's reactive is not the same as Vue, including the Compostion API.

File: website/src/components/UI/Affix.tsx (hunk 2 above)
Comment (barchielAbyss) [reply website/src/components/UI/Affix.tsx]: there is look like escape SSR build error? I met it today..😂, let me check how to modify~ https://app.netlify.com/sites/apache-apisix/deploys/628a20980921c8000875641f

File: website/src/components/UI/Affix.tsx (hunk 3 above)
Comment (barchielAbyss) [reply website/src/components/UI/Affix.tsx]:
```ts
interface Props {
  style: CSSProperties;
  children: ReactNode;
}
```

the props has customized `style` key,  i can't immediate use it

File: website/src/components/UI/Affix.tsx (hunk 2 above)
Comment (SkyeYoung) [reply website/src/components/UI/Affix.tsx]: You may need to focus on dependency arrays 🤔

File: website/src/components/UI/Affix.tsx (hunk 4 above)
Comment (barchielAbyss) [reply website/src/components/UI/Affix.tsx]: image

like this, really is `props.style.top` 😂

**Comment by barchielAbyss** [comment]
> React's reactive is not the same as Vue, including the Compostion API.

I'll go through the React documentation again

File: website/src/components/UI/Affix.tsx (hunk 4 above)
Comment (SkyeYoung) [reply website/src/components/UI/Affix.tsx]: I mean, is it a number or a string? Is it possible to write it in a way that is not a template string?

File: website/src/components/UI/Affix.tsx (hunk 3 above)
Comment (SkyeYoung) [reply website/src/components/UI/Affix.tsx]: You can remove the `children` prop.

image

File: website/src/components/UI/Affix.tsx (hunk 2 above)
Comment (barchielAbyss) [reply website/src/components/UI/Affix.tsx]: > You may need to focus on dependency arrays 🤔

It was a good learning experience, THX ☺️ 

https://github.com/streamich/react-use/blob/e53ca94a0b1f20270b0f75dc2ca1fecf1e119dde/src/useEffectOnce.ts#L3

**Comment by barchielAbyss** [comment]
@SkyeYoung  I have fixed most of the errors in the code, please review it again

**Review by SkyeYoung — APPROVED** [review]

**Comment by barchielAbyss** [comment]
@juzhiyuan This is a styling issue that was fixed last week, please help review it if you have time, thanks :)

**Review by juzhiyuan — APPROVED** [review]

**Review by yzeng25 — APPROVED** [review]
