### PR TITLE
fix: added proper redirection to ingress-controller docs

### LINKED ISSUE #1974: Documentation --> API Ingress Controller --> Page not found
Good day!
When trying to get to the API Ingress Controller documentation, I am getting a 404 error.

Image

Image

Thank you for fixing this!

### PR DESCRIPTION
**Pull request by ayush00git**
Fixes: #1974 and #1972 

Changes I made:

/config/docs.js and /config/downloads.js gave the property "firstDocPath" a value = /getting-started which didn't existed for the ingress-controller docs so instead i changed its value to /overview which was also opening the docs when clicked via Navbar.

Now the issue of 404 Page Not Found while clicking on the card of ingress controller is resolved.
Thanks

### CODE REVIEW

**Comment by ayush00git** [comment]
Hey @yzeng25 @Yilialinn can you review my PR, actually the site redirects to a wrong URL leading to a 404 error, i have made some changes to redirect it to the right URL and now it's working fine.
Please give it a look and do guide me through the changes if something is left.
Thanks :)

File: config/docs.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ module.exports = [
     githubRepo: 'apache/apisix-ingress-controller',
     version: '1.6.0',
     releaseDate: '2022-12-30',
```
Comment (yzeng25) [inline config/docs.js]: Should these 2 be updated as well? Loop @SkyeYoung  @juzhiyuan @AlinsRan 

https://github.com/apache/apisix-ingress-controller/releases/tag/2.0.0
```suggestion
    version: '2.0.0',
    releaseDate: '2025-12-17',
```

File: config/downloads.js [hunk 2]
```diff
@@ -27,7 +27,7 @@ module.exports = [
     dockerhubPath: 'apisix-ingress-controller',
     version: '1.6.0',
     releaseDate: '2022-12-30',
```
Comment (yzeng25) [inline config/downloads.js]: ditto

File: config/docs.js [hunk 3]
```diff
@@ -19,7 +19,7 @@ module.exports = [
...
-    firstDocPath: '/getting-started',
```
Comment (yzeng25) [inline config/docs.js:22]: Change in this line was previously made by @SkyeYoung in https://github.com/apache/apisix-website/commit/a9669fdfdf0f6bd7f2c022a24a99c13c6d621e6a , PTAL.

File: config/downloads.js [hunk 4]
```diff
@@ -27,7 +27,7 @@ module.exports = [
...
-    firstDocPath: '/getting-started',
```
Comment (yzeng25) [inline config/downloads.js:30]: ditto PTAL @SkyeYoung

**Comment by ayush00git** [comment]
Hey, @yzeng25 
Thanks for the review!

The main intent of this PR was to fix the 404 caused by `firstDocPath` pointing to `/getting-started`, which no longer exists for ingress-controller docs. Changing it to `/overview` resolves the broken link.

Regarding the version and releaseDate:
I noticed they are outdated, but I wasn’t sure if updating them should be part of this PR or handled separately. I’m happy to update them to the latest release (2.0.0) if that’s preferred.

Please let me know how you’d like me to proceed.

File: config/downloads.js (hunk 2 above)
Comment (Baoyuantop) [reply config/downloads.js]: Hi @ayush00git, this needs to be modified as well.

Comment (ayush00git) [reply config/downloads.js]: > Hi @ayush00git, this needs to be modified as well.

Hii @Baoyuantop thanks for the review, i'll quickly make the changes and push the commit : )

**Comment by ayush00git** [comment]
Hey @Baoyuantop 
I've made the requested changes, please go through the PR and let me know, how to proceed : )

**Review by Baoyuantop — APPROVED** [review]

**Review by SkyeYoung — APPROVED** [review]
