### PR TITLE
fix: showing Project's name on the navbar

### LINKED ISSUE #424: Support showing Project's name on the navbar
When we visit FAQ from the `FAQ` dropdown:

image

It will show `Docs`:

image

**Expected behavior**

It will show the target repo's name:

image

Maybe related to https://github.com/apache/apisix-website/blob/master/website/src/theme/DocPage/index.js#L41 ?

### PR DESCRIPTION
**Pull request by Baoyuantop**
Fixes: #424 

Changes:
After selecting the FAQ of different projects, the Docs option will display the corresponding project name.

Screenshots of the change:

image

image

image

### CODE REVIEW

File: website/src/theme/DocPage/index.js [hunk 1]
```diff
@@ -35,16 +35,19 @@ function DocPageContent({ currentDocRoute, versionMetadata, children }) {
     apisixHelmChart : "seeking-help",
     apisixDocker : "build-an-image-from-source",
     apisixJavaPluginRunner : "overview",
-    apisixGoRunner : "prerequisites"
+    apisixGoRunner : "prerequisites",
+    apisixFAQ: "why-a-new-api-gateway",
```
Comment (juzhiyuan) [inline website/src/theme/DocPage/index.js]: Maybe not a good idea to use this way, because if the FAQ file gets updated, website will not know it should get updated, too.

**Review by KishaniKandasamy — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by iamayushdas — APPROVED** [review]
Nicely done , thanks

**Review by tokers — APPROVED** [review]
