### PR TITLE
fix: update ingress controller download link

### LINKED ISSUE #765: bug: Ingress Controller version does not match the download link
**Actual Behaviour**

The current Ingress Controller version number does not match the download link, this has been corrected in this PR.

**Expected Behaviour**

Provide the correct download link.

**Steps to reproduce it**

1. Open this link `https://apisix.apache.org/downloads/`
2. Check APISIX® Ingress Controller Download link

**Screenshots**

msedge_2021-11-23_09-40-02

### PR DESCRIPTION
**Pull request by bzp2010**
Fixes: #765

Changes:

The current Ingress Controller version number does not match the download link, this has been corrected in this PR.

### CODE REVIEW

**Review by tzssangglass — APPROVED** [review]

File: website/config/downloads.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ module.exports = [
     color: "#2563EB",
     githubRepo: "apache/apisix-ingress-controller",
     githubBranch: "master",
-    downloadPath: "apisix/ingress-controller/1.2.0/apache-apisix-ingress-controller-1.2.0-src",
+    downloadPath: "apisix/ingress-controller/1.3.0/apache-apisix-ingress-controller-1.3.0-src",
     version: "1.3.0",
     releaseDate: "2021-10-17",
```
Comment (juzhiyuan) [inline website/config/downloads.js:39]: date?

**Review by juzhiyuan — APPROVED** [review]
