### PR TITLE
fix: switch color modes in multiple tabs

### LINKED ISSUE #871: A strange problem caused by switching color modes in multiple tabs
**Actual Behaviour**

If you open the docs in another tab and switch to dark mode, when you return to the home page in the original tab, the home page will also switch to dark mode

**Expected Behaviour**

Maybe it should be reset to light mode? Or, I think it's possible to add a toggle button to the homepage as well. It's also good if the homepage has a good dark mode.

**Steps to reproduce it**

It's hard to describe, and I'll give a gif.

**Screenshots of the issue**

apisix-problem

**Would you like to work on the issue?**

Yes, but before that, I need to know the community's opinion.

### PR DESCRIPTION
**Pull request by SkyeYoung**
Fixes: #871

Changes:

Add `isDarkTheme` to `useEffect`'s deps array.

Screenshots of the change:

none

### CODE REVIEW

**Comment by SkyeYoung** [comment]
@bzp2010 please give me some suggestions and reviews 😳

Anyone is welcome to review this pr. Thank you!

**Review by Baoyuantop — APPROVED** [review]

**Review by oil-oil — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

File: website/src/pages/index.js [hunk 1]
```diff
@@ -28,14 +28,14 @@ const useWindowSize = () => {
 const ThemeResetComponent = () => {
   const {isDarkTheme, setLightTheme, setDarkTheme} = useThemeContext();
 
-  useEffect(() => {    
+  useEffect(() => {
     const children = document.querySelector(".navbar__items--right").childElementCount;
     document.querySelector(".navbar__items--right").childNodes[children-2].style.display = "none";
 
     if(isDarkTheme) {
```
Comment (juzhiyuan) [inline website/src/pages/index.js:35]: How about using `setLightTheme(!isDarkTheme)`?

Comment (SkyeYoung) [reply website/src/pages/index.js:35]: @juzhiyuan Do you mean：
```diff
- if(isDarkTheme){
-   setLightTheme(true);
- }
+ setLightTheme(!isDarkTheme)
```
I have no plans to change this part of the code. 😳
But, I'll try it.
I think this might make the function execute more times. I'll check it right way.

Comment (SkyeYoung) [reply website/src/pages/index.js:35]: @juzhiyuan Sorry, I made a mistake. The intent of this part of the code is to reset the color mode to `light mode`. The above changes will not achieve this goal

If you mean, just change `setLightTheme(true)`  to `setLightTheme(!isDarkTheme)`. I think it might be clearer to use `ture` as a parameter.

Comment (SkyeYoung) [reply website/src/pages/index.js:35]: @juzhiyuan so I don't think it should be changed. 😅

**Review by bzp2010 — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]
