### PR TITLE
Fix: Added redirection to GitHub index when no hash present

### LINKED ISSUE #1783: docs: editing url valid
### Current State

in this [url](https://apisix.apache.org/edit/) and  this [url](https://apisix.apache.org/zh/edit/);
There is no response when clicking this button and it will not jump to other pages.
image

### Desired State

Automatically jump to the warehouse where modifications can be submitted

### PR DESCRIPTION
**Pull request by siyaramsujan**
Fixes: #1783

Changes:

Added redirection to the GitHub repository index when the path variable is empty.

### CODE REVIEW

File: doc/src/pages/edit.tsx [hunk 1]
```diff
@@ -20,18 +22,26 @@ const Edit: FC = () => {
...
   }, []);
 
   const edit = useCallback(() => {
-    let path = getPath();
+    const path = getPath();
+
     if (!pathExist) {
-      const pathArr = path.replace('edit', 'new').split('/');
-      pathArr[pathArr.length - 1] = `?filename=${pathArr.at(-1)}`;
-      path = pathArr.join('/');
```
Comment (pottekkat) [inline doc/src/pages/edit.tsx]: Not sure if this is ever run but it seems like it is for creating a new file if doesn't exist?

Should we replace this logic?

Maybe instead we can add to this logic and set a new condition for an empty path. Because path does not exist and path is empty are different.

Again, I'm not sure if it is ever run so IDK if it would be any problem.

Comment (siyaramsujan) [reply doc/src/pages/edit.tsx]: Hi, It looks like the code isn't creating new files. 

I think it's attempting to replace the path, for example, from '/edit/#githubrepolink' to '/new/?filename=githubrepolink' if it doesn't exist. But, we're using getPath = () => window.location.hash.slice(1); to retrieve the path, which only gives us the hash - "githubrepolink'".

So, it seems that this logic isn't being utilized. Please correct me if I'm wrong. Thanks!

Comment (pottekkat) [reply doc/src/pages/edit.tsx]: I'm not sure, I will check with @SkyeYoung

Comment (siyaramsujan) [reply doc/src/pages/edit.tsx]: Sure, Thank you for your review, @pottekkat.

**Review by SkyeYoung — APPROVED** [review]

**Comment by SkyeYoung** [comment]
Thanks for the contribution! The logic should be fine.

cc @bzp2010 @guoqqqi pls review this

File: doc/src/pages/edit.tsx [hunk 2]
```diff
@@ -20,18 +22,26 @@ const Edit: FC = () => {
     const path = getPath();
 
     setIsLoading(true);
+
+    if (path === '' || !path.includes('https://github.com/apache')) {
+      setPathExist(false);
+      setIsLoading(false);
+      return;
+    }
```
Comment (SkyeYoung) [inline doc/src/pages/edit.tsx]: You can move this part of the code up 24 lines, you should not need to `setIsLoading(false)` this way.

Also `if(xxx)` can be written as `if(!path?.includes(INDEX_URL))` 🤔

File: doc/src/pages/edit.tsx (hunk 1 above)
Comment (SkyeYoung) [reply doc/src/pages/edit.tsx]: This logic will actually jump to the github url of "Create a new file". 

The working logic is: The document site uses English as fallback, and when documents in Chinese or other languages ​​do not exist, they will automatically be displayed in English. But at this time, `edit url` will still use the path of the corresponding language. 

For example, `/xxx` exists, but the document `/zh/xxx` does not exist. Assume that the edit url of the latter is `github/zh/xxx`. Since the document does not exist at this time, the content in `/xxx` will be displayed, but the edit url Still `github/zh/xxx`. Apparently at this point, (at least I thought so,) clicking this link should create this non-existent `/zh/xxx`.

Comment (SkyeYoung) [reply doc/src/pages/edit.tsx]: If you follow your modified logic, it should jump directly to a non-existent path, causing github to display 404.

So I think this current logic needs to be adjusted.

Comment (SkyeYoung) [reply doc/src/pages/edit.tsx]: Here is a practical example, please find the edit url link in the page 

https://apisix.apache.org/zh/docs/apisix/tutorials/manage-api-consumers/

**Review by SkyeYoung — CHANGES_REQUESTED** [review]
I review it again. There are some problems. Please adjust them, Thx 😸

File: doc/src/pages/edit.tsx (hunk 1 above)
Comment (siyaramsujan) [reply doc/src/pages/edit.tsx]: Hi @SkyeYoung, Thanks for explaining. I finally understand how it's supposed to work, I had misunderstood before. The modified logic should redirect the user to the index URL if it doesn't exist. Should I revert it back to the logic of redirecting to GitHub create new file? Thanks again.

File: doc/src/pages/edit.tsx (hunk 2 above)
Comment (siyaramsujan) [reply doc/src/pages/edit.tsx]: Thanks for the review, @SkyeYoung. I'll move that code up and use `if (!path?.includes(INDEX_URL))` as you suggested. By the way, I'm currently using `INDEX_URL` as `https://github.com/apache/apisix` is that okay? Thanks!

Comment (SkyeYoung) [reply doc/src/pages/edit.tsx]: I think it's okay.

File: doc/src/pages/edit.tsx (hunk 1 above)
Comment (SkyeYoung) [reply doc/src/pages/edit.tsx]: @siyaramaa Yes. Sorry for replying so late.

**Comment by siyaramsujan** [comment]
Thank you, I have just made the update.

**Review by yzeng25 — APPROVED** [review]

**Comment by yzeng25** [comment]
PTAL @SkyeYoung

**Review by SkyeYoung — APPROVED** [review]
